web:
  build: .
  links:
   - db
  ports:
   - "3005:3005"
  volumes:
   - ./:/home/mean
  environment:
   NODE_ENV: development
db:
  image: mongo
  volumes:
   - ./runtime/mongo:/data/db
  ports:
   - "27018:27017"
